"""empty message

Revision ID: 173df6bb3d9b
Revises: 5b7d846f45ab
Create Date: 2023-04-30 15:23:17.802280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '173df6bb3d9b'
down_revision = '5b7d846f45ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qc', schema=None) as batch_op:
        batch_op.alter_column('l_phone',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qc', schema=None) as batch_op:
        batch_op.alter_column('l_phone',
               existing_type=sa.String(length=200),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
