"""empty message

Revision ID: 4e9d3e5569c8
Revises: 
Create Date: 2023-04-06 17:52:04.758283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9d3e5569c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('authority', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('industry_division', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=200), nullable=False),
    sa.Column('property_range', sa.String(length=200), nullable=False),
    sa.Column('size', sa.String(length=200), nullable=False),
    sa.Column('data', sa.String(length=200), nullable=False),
    sa.Column('traceability_certification_documents', sa.String(length=200), nullable=False),
    sa.Column('quality_assessment_report', sa.String(length=200), nullable=False),
    sa.Column('audit_status', sa.String(length=200), nullable=False),
    sa.Column('format', sa.String(length=200), nullable=False),
    sa.Column('begin_time', sa.DateTime(), nullable=False),
    sa.Column('renew_time', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_status', sa.String(length=200), nullable=False),
    sa.Column('c_unified_social_credit_code', sa.String(length=200), nullable=False),
    sa.Column('c_name', sa.String(length=200), nullable=False),
    sa.Column('c_type', sa.String(length=200), nullable=False),
    sa.Column('c_scrope', sa.String(length=200), nullable=False),
    sa.Column('b_license_type', sa.String(length=200), nullable=False),
    sa.Column('b_license', sa.String(length=200), nullable=False),
    sa.Column('m_name', sa.String(length=200), nullable=False),
    sa.Column('m_phone', sa.Integer(), nullable=False),
    sa.Column('m_license_type', sa.String(length=200), nullable=False),
    sa.Column('m_license', sa.String(length=200), nullable=False),
    sa.Column('b_account', sa.String(length=200), nullable=False),
    sa.Column('b_bank', sa.String(length=200), nullable=False),
    sa.Column('b_account_name', sa.String(length=200), nullable=False),
    sa.Column('b_institution', sa.String(length=200), nullable=False),
    sa.Column('b_account_info', sa.String(length=200), nullable=False),
    sa.Column('l_name', sa.String(length=200), nullable=False),
    sa.Column('l_area', sa.String(length=200), nullable=False),
    sa.Column('l_address', sa.Text(), nullable=False),
    sa.Column('l_code', sa.Integer(), nullable=False),
    sa.Column('l_email', sa.String(length=200), nullable=False),
    sa.Column('l_website', sa.String(length=200), nullable=False),
    sa.Column('l_phone', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('audit_status', sa.String(length=200), nullable=False),
    sa.Column('market_status', sa.String(length=200), nullable=False),
    sa.Column('nominal_price', sa.Integer(), nullable=True),
    sa.Column('pre_img', sa.String(length=200), nullable=True),
    sa.Column('products_description', sa.Text(), nullable=True),
    sa.Column('application_scenario', sa.Text(), nullable=True),
    sa.Column('data_asset_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_asset_id'], ['data_asset.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaciton_contract',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('time_limit', sa.DateTime(), nullable=False),
    sa.Column('data_products_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['data_products_id'], ['data_products.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaciton_contract')
    op.drop_table('data_products')
    op.drop_table('qc')
    op.drop_table('data_asset')
    op.drop_table('account')
    # ### end Alembic commands ###
