"""empty message

Revision ID: 9e860869aee4
Revises: 4e9d3e5569c8
Create Date: 2023-04-22 14:03:42.638091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e860869aee4'
down_revision = '4e9d3e5569c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('c_license_type', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('c_license', sa.String(length=200), nullable=False))
        batch_op.drop_column('b_license')
        batch_op.drop_column('b_license_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('b_license_type', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('b_license', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('c_license')
        batch_op.drop_column('c_license_type')

    # ### end Alembic commands ###
