"""empty message

Revision ID: a6f2270cb59d
Revises: 9e860869aee4
Create Date: 2023-04-23 22:48:10.533789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6f2270cb59d'
down_revision = '9e860869aee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_range', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('time_limit', sa.DateTime(), nullable=False))

    with op.batch_alter_table('qc', schema=None) as batch_op:
        batch_op.alter_column('l_area',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=200),
               nullable=False)

    with op.batch_alter_table('transaciton_contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tradding_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('effective_or_not', sa.String(length=200), nullable=False))
        batch_op.drop_column('price')
        batch_op.drop_column('time_limit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaciton_contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('effective_or_not')
        batch_op.drop_column('tradding_time')

    with op.batch_alter_table('qc', schema=None) as batch_op:
        batch_op.alter_column('l_area',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=200),
               nullable=True)

    with op.batch_alter_table('data_products', schema=None) as batch_op:
        batch_op.drop_column('time_limit')
        batch_op.drop_column('property_range')

    # ### end Alembic commands ###
