"""empty message

Revision ID: c18c79444f9c
Revises: a6f2270cb59d
Create Date: 2023-04-30 15:21:44.196384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c18c79444f9c'
down_revision = 'a6f2270cb59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qc', schema=None) as batch_op:
        batch_op.alter_column('m_phone',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qc', schema=None) as batch_op:
        batch_op.alter_column('m_phone',
               existing_type=sa.String(length=200),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
